name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: compile
      run: mvn clean compile 
    - name: test
      run: mvn clean test 
    - name: Build with package
      run: mvn clean package --file pom.xml  
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target 
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{squ_47d1907e7ac63876ed151a4b1516076148c0ff6c }}
        SONAR_HOST_URL: ${{ http://52.146.20.111:9000 }}   
      


